#!/bin/bash

cd "$(dirname "${BASH_SOURCE}")"

info () {
  printf "\e[0m$1\n"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

setup_dotfiles () {
  info 'Setup dotfiles'

  ln -s ~/.config/dotfiles/bashrc ~/.bash_profile
  ln -s ~/.config/dotfiles/bashrc ~/.bashrc

  success 'Setup dotfiles'
}

setup_tmux () {
  info 'Setup tmux files'

  ln -s ~/.config/dotfiles/tmux/tmux.conf ~/.tmux.conf

  success 'Setup tmux'
}

setup_git () {
  info 'Setup git'

  user 'What is your name?'
  read name

  user 'What is your email?'
  read email

  `git config --global user.name "$name"`
  `git config --global user.email "$email"`
  `git config --global include.path "~/.config/dotfiles/git/gitconfig"`
  `git config --global core.excludesfile "~/.config/dotfiles/git/gitignore"`

  success 'Setup git'
}

echo ''

setup_dotfiles
setup_tmux
setup_git
