#!/usr/bin/env bash

if ! pgrep -x tmux > /dev/null; then
    echo "There are no open tmux sessions or the tmux server is not running."
    exit 1
fi

sessions=$(tmux list-sessions -F "#{session_name}" 2>/dev/null)

if [[ -z $sessions ]]; then
    echo "There are no available tmux sessions."
    exit 1
fi

selected_session=$(echo "$sessions" | fzf --height=10 --header="Select a tmux session:")

if [[ -z $selected_session ]]; then
    echo "No session has been selected."
    exit 1
fi

if [[ -n $TMUX ]]; then
    tmux switch-client -t "$selected_session"
else
    tmux attach-session -t "$selected_session"
fi
